"""empty message

Revision ID: 2021aa649d87
Revises: 7e370ef10c33
Create Date: 2024-12-08 15:11:54.011801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2021aa649d87'
down_revision: Union[str, None] = '7e370ef10c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_id_key', 'user', type_='unique')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_user_id_key', 'user', ['user_id'])
    # ### end Alembic commands ###
