"""Assignment: add time, Report: add is_accepted

Revision ID: 3d8491c042f1
Revises: b9574f244163
Create Date: 2024-12-26 13:55:16.409271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d8491c042f1'
down_revision: Union[str, None] = 'b9574f244163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('check_date', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.drop_column('report', 'accept_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('accept_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('report', 'is_accepted')
    op.drop_column('report', 'check_date')
    # ### end Alembic commands ###
